version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PW=password
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_NAME=UserManagment